### ISSUE TITLE
CRITICAL: Code does not compile

### ISSUE THREAD

**Issue by martinjonsson01** [adiwir/TDA553-lab1#26]
```
Exception in thread "main" java.lang.Error: Unresolved compilation problems:
        Position cannot be resolved to a type
        Storage cannot be resolved to a type
        Storage cannot be resolved to a type
        Storage cannot be resolved to a type
        Position cannot be resolved to a type
        Position cannot be resolved to a type
        Storage cannot be resolved to a type
        Storage cannot be resolved to a type
        Position cannot be resolved to a type
        Position cannot be resolved to a type
        Storage cannot be resolved to a type
        Position cannot be resolved to a type
        Position cannot be resolved to a type
        Storage cannot be resolved to a type

        at CarRepairShop.<init>(CarRepairShop.java:10)
        at Main.main(Main.java:5)
```

**Comment by JacobAndersso** [comment]
We've removed the Main file since we didn't need it. Either way we weren't able to reproduce the problem you describe since it compiles for us

**Comment by martinjonsson01** [comment]
I see. If you've made any changes to the code since submitting it under the tag `Lab3`, please make a new tag.

**Comment by martinjonsson01** [comment]
I'll close this since it seems resolved, but don't forget to create a new tag after having solved the other critical issue! :)
